### ISSUE TITLE
Unable To Build OR RUN PERIOD NEED ASSISTANCE

### ISSUE THREAD

**Issue by Rkayedion** [seed-cat/seedcat#5]
really appreciate the tool it is built exactly for the things i need to do but do to being on. a mac ive had issues, first i downloaded parallels then installed windows 11 then installed ubuntu and yet im still having issues.. ive been working on cracking this wallet for 6 months.. i started with 12 different seed list and all of them had some type of mistakes... before. i through in the towel i found your code and it gave me hope for that finderouter was a bust for me at least.... I apologize for the wordy comment but wanted you to have my back story and know my frustration to feeling  like i cant believe the one build that was designed for the issues i have i cant build... i have narrowed it down from. 12 seperate word phrases to just 3 phrases.... SOME ONE PLEASE TELL ME HOW I CAN BUILD THIS CODE SEEDCAT OR SOMEHOW JUST RUN IT... I am A noob but feel ive caught on quickly appreciate the tool it is built exactly for the things i need to do but do to being on. a mac ive had issues, first i downloaded parallels then installed windows 11 then installed ubuntu and yet Im still having issues.. ive been working on cracking this wallet for 6 months.. i started with 12 different seed list and all of them had some type of mistakes... before. i through in the towel i found your code and it gave me hope for that finderouter was a bust for me at least.... I apologize for the wordy comment but wanted you to have my back story and know my frustration to feeling  like i cant believe the one build that was designed for issues like mine i cant figure out how to run it build it... Nothing SO LOST SOME ONE PLEASE HELP THIS NOOB FIGURE THIS OUT.... If what someone shows me to do works then I will give them a legit kickback.... THANK YOU!!

**Comment by seed-cat** [comment]
Hi,

Can you explain what happens when you try to run on Ubuntu?

You will need to install Cuda before you run. I believe the command is:
sudo apt-get install nvidia-cuda-toolkit

Next, do you know what mistakes have been made? Are the words in order? Are words missing or partially wrong? Was there a passphrase?

With 3 wrong words recovery should be possible. Here are some examples of seed word recovery:
https://github.com/seed-cat/seedcat/blob/master/docs/recovery.md

**Comment by seed-cat** [comment]
If you have trouble running you can also try to run it in the cloud.
https://github.com/seed-cat/seedcat/blob/master/docs/renting.md

You can rent GPUs anonymously and pay in bitcoin. This may speed up your recovery quite a bit if you don't have a powerful GPU. I have used them to recover funds before.

**Comment by Rkayedion** [comment]
HERE  is My issues that i need help with.. i have a mac so i used parallels to have windows 11 and ubuntu and every tim i try with github and video studio code i just cant seem to get this thing to get built or just to run im going crazy for what you have here is EXACTLY WHAT I NEED PLEASE HELP!!!! sorry im such a noob but i have been on this for over 6months and your program is what sparked this new refound drive that i have to take control of my old crypto assets

**Comment by seed-cat** [comment]
What error do you get trying to run it?

How did you install CUDA Toolkit?

To build you can follow the instructions here: https://github.com/seed-cat/seedcat/blob/master/scripts/release.sh

I can't help you without information.

**Comment by Rkayedion** [comment]
sorry i wasnt to clear. i am sorta a noobie.. i have a mac and seedcat runs on windows or linux so i got parallels and down loaded windows and tried to down load ubuntu and when i execute the seedcat.exe on win 11 it goes to open and just fails i dont know what im doing wrong... i really need to somehow get this built or be able to run it some where...

seperate question when im in the terminal what do i type to get it going like for btcrecover i have to type python3.11 seedrecovery.py then all the permiters like address typos and what not but your seed-cat is what i really need to be running for btcr doesnt have options where you can give it the first and second letter with an anchor that is amazing and once im able to get this system of yours riunning and finally get back into my wallets i will be making a contribution... so thank you looking forward to getting your reply so i can get this going

**Comment by seed-cat** [comment]
I'd recommend running on Ubuntu, but first make sure to install the CUDA toolkit.

You just need to run ./seedcat in the folder. If you have trouble with command-line tools, I'd recommend just renting a vast.ai machine because it'll be setup with CUDA already for you.

If you want I can walk you through the steps via a chat, just send me an email.

**Comment by Rkayedion** [comment]
that would be amazing if after i do all this downloading  {While downloading and installing CUDA it had said that i should download Visual Studios first, which was a whole other nightmare for there was so much to that and i wasnt sure what was manditory to have to be able to build and run seedcat for there was so many options for it at first the install was at about 46gb but. i narrowed it down to like 16 which at this point i might im wondering what all do i have to have to just be able to run and build seedcat that way i dont waste so much room with all these extra bells and whistles.. for between parallels windows 11 cuda and ubuntu i was maxed out with available space so now with this visual studio im having to go into my sytem and delete any little thing i dont need and even with me doing that im not sure ill have enough room lol

**Comment by seed-cat** [comment]
Please reach out to @seedcat:matrix.org using Matrix or email ***@***.*** rather than discuss in the issue.
