### ISSUE TITLE
Intel OpenCL build failure

### ISSUE THREAD

**Issue by phicyclist** [seed-cat/seedcat#6]
In testing I am able to obtain platform information from `clinfo` and can successfully run benchmarks for other hashcat modules, but m28510 encounters a build failure. This has occurred in Ubuntu 24.04 and fully updated NixOS on an Intel UHD 620 chipset.

First occurrence: https://github.com/seed-cat/hashcat/blob/2772ee58a442b000f666056bb0d195baedf377f0/OpenCL/m28510-pure.cl#L483

> clCompileProgram(): CL_COMPILE_PROGRAM_FAILURE
> 
> 1:483:33: error: passing '__global u32 *' (aka '__global unsigned int *') to parameter of type 'const __private u32 *' (aka 'const __private unsigned int *') changes address space of pointer
  pw_index = bip39_guess_words (pws[gid].i, salt_bufs[SALT_POS_HOST].salt_buf, words);
                                ^~~~~~~~~~
/home/user/src/seedcat/hashcat/OpenCL/inc_bip39.cl:232:56: note: passing argument to parameter 'password' here
DECLSPEC u32 bip39_guess_words (PRIVATE_AS const u32 * password, PRIVATE_AS const u32 * salt, PRIVATE_AS u32 * wordlist)
                                                       ^
1:494:43: error: passing '__global u32 *' (aka '__global unsigned int *') to parameter of type 'const __private u32 *' (aka 'const __private unsigned int *') changes address space of pointer
  encode_passphrase (&passphrase_encoder, pws[gid].i, pws[gid].pw_len, pw_index);
                                          ^~~~~~~~~~
1:131:93: note: passing argument to parameter 'password' here
DECLSPEC void encode_passphrase (PRIVATE_AS msg_encoder_t * encoder, PRIVATE_AS const u32 * password, PRIVATE_AS const u32 password_len, PRIVATE_AS const u32 start_index)
                                                                                            ^
1:617:14: error: initializing 'const __private u32 *__private' (aka 'const __private unsigned int *__private') with an expression of type 'const __global u32 *' (aka 'const __global unsigned int *') changes address space of pointer
  const u32 *derivation_end = &salt_bufs[SALT_POS_HOST].salt_buf[1];
             ^                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1:620:19: error: passing '__global u32 *' (aka '__global unsigned int *') to parameter of type '__private u32 *' (aka '__private unsigned int *') changes address space of pointer
  init_derivation(tmps[gid].derivation_path, derivation_end);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
1:414:49: note: passing argument to parameter 'derivation_path' here
DECLSPEC bool init_derivation (PRIVATE_AS u32 * derivation_path, PRIVATE_AS const u32 * derivation_end)
                                                ^
1:631:8: error: initializing '__private u64 *__private' (aka '__private unsigned long *__private') with an expression of type '__global u64 *' (aka '__global unsigned long *') changes address space of pointer
  u64 *seed = tmps[gid].out;
       ^      ~~~~~~~~~~~~~
1:633:14: error: initializing 'const __private u32 *__private' (aka 'const __private unsigned int *__private') with an expression of type 'const __global u32 *' (aka 'const __global unsigned int *') changes address space of pointer
  const u32 *derivation_end = &salt_bufs[SALT_POS_HOST].salt_buf[1];
             ^                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1:634:8: error: initializing '__private u32 *__private' (aka '__private unsigned int *__private') with an expression of type '__global u32 *' (aka '__global unsigned int *') changes address space of pointer
  u32 *derivation_path = tmps[gid].derivation_path;
       ^                 ~~~~~~~~~~~~~~~~~~~~~~~~~

`* Device #1: Kernel /home/user/src/seedcat/hashcat/OpenCL/m28510-pure.cl build failed.`

**Comment by seed-cat** [comment]
Sorry for the late response, but it looks like an issue with the version of OpenCL you have installed.

If you are having trouble locally you could try to follow the cloud instructions:
https://github.com/seed-cat/seedcat/blob/master/docs/renting.md
