### ISSUE TITLE
Seems not to be recognizing the password i inserted

### ISSUE THREAD

**Issue by FredianoCampione** [seed-cat/seedcat#8]
i created a test address
checked before on iancole's website

![image](https://github.com/user-attachments/assets/dbb2b6a2-9eb7-44e1-b964-0c1ee7cd5198)

using .exe on windows 11

seedcat --address bc1qfr572nlyps4gmw7jumsg4w6h0t9nz8x56zth67 --seed "hero direct wisdom wool expect clerk waste casino estate burden agent try" --derivation "m/84'/0'/0'/0" -p ./dizionario.txt

dictionary file has 1  word "test"
Still it doesn find the passphrase
____________________________________________________________________________________________________
D:\seedcat>seedcat --address bc1qfr572nlyps4gmw7jumsg4w6h0t9nz8x56zth67 --seed "hero direct wisdom wool expect clerk waste casino es                                                                                                           state burden agent try" --derivation "m/84'/0'/0'/0" --passphrase dizionario.txt

============ Seedcat Configuration ============
P2WPKH (Native Segwit) Address: bc1qfr572nlyps4gmw7jumsg4w6h0t9nz8x56zth67

Derivations: 1
 Begin: m/84'/0'/0'/0
 End:   m/84'/0'/0'/0

Seeds: 1
 Begin: hero,direct,wisdom,wool,expect,clerk,waste,casino,estate,burden,agent,try
 End:   hero,direct,wisdom,wool,expect,clerk,waste,casino,estate,burden,agent,try

Passphrases: 1
 Begin: dizionario.txt
 End:   dizionario.txt

Total Guesses: 1
 Stdin Mode: CPU-limited due to not enough passphrases to guess
 Warning: For better security turn off your internet connection

Continue with recovery [Y/n]? n

D:\seedcat>seedcat --address bc1qfr572nlyps4gmw7jumsg4w6h0t9nz8x56zth67 --seed "hero direct wisdom wool expect clerk waste casino es                                                                                                           state burden agent try" --derivation "m/84'/0'/0'/0" -p ./dizionario.txt

============ Seedcat Configuration ============
P2WPKH (Native Segwit) Address: bc1qfr572nlyps4gmw7jumsg4w6h0t9nz8x56zth67

Derivations: 1
 Begin: m/84'/0'/0'/0
 End:   m/84'/0'/0'/0

Seeds: 1
 Begin: hero,direct,wisdom,wool,expect,clerk,waste,casino,estate,burden,agent,try
 End:   hero,direct,wisdom,wool,expect,clerk,waste,casino,estate,burden,agent,try

Passphrases: 1
 Begin: test
 End:   test

Total Guesses: 1
 Stdin Mode: CPU-limited due to not enough passphrases to guess
 Warning: For better security turn off your internet connection

Continue with recovery [Y/n]? y

============ Seedcat Recovery ============
Writing Dictionary 'hc_left.gz' 100.00% (1/1)

Writing Hashes 100.00% (1/1)

Waiting for GPU initialization please be patient...
* Device #1: NVIDIA RTX A5000, 23282/24563 MB, 64MCU
                                                                                                                        
Recovery Guesses                                                                                                        
 Progress: 0.00% (0/1)                                                                                                  

Recovery Guesses
 Progress: 0.00% (0/1)
 Speed....: 0/sec
 GPU Speed: 0/sec
 ETA......: Unknown
 Elapsed..: 4 secs

Error: Exhausted search with no results...try with different parameters

**Comment by seed-cat** [comment]
Your derivation path is missing a `0`, it should be `m/84'/0'/0'/0/0` so that might be your issue.

The following is the result on my machine:
```
./seedcat --address bc1qfr572nlyps4gmw7jumsg4w6h0t9nz8x56zth67 --seed "hero direct wisdom wool expect clerk waste casino estate burden agent try" --derivation "m/84'/0'/0'/0/0" -p ./dizionario.txt

============ Seedcat Configuration ============
P2WPKH (Native Segwit) Address: bc1qfr572nlyps4gmw7jumsg4w6h0t9nz8x56zth67

Derivations: 1
 Begin: m/84'/0'/0'/0/0
 End:   m/84'/0'/0'/0/0

Seeds: 1
 Begin: hero,direct,wisdom,wool,expect,clerk,waste,casino,estate,burden,agent,try
 End:   hero,direct,wisdom,wool,expect,clerk,waste,casino,estate,burden,agent,try

Passphrases: 1
 Begin: test
 End:   test

Total Guesses: 1
 Stdin Mode: CPU-limited due to not enough passphrases to guess

Continue with recovery [Y/n]? Y

============ Seedcat Recovery ============
Writing Dictionary 'hc_left.gz' 100.00% (1/1)

Writing Hashes 100.00% (1/1)

Waiting for GPU initialization please be patient...
* Device #1: NVIDIA GeForce RTX 4090, 23398/24111 MB, 128MCU

Recovery Guesses
 Progress: 0.00% (0/1)
 Speed....: 0/sec
 GPU Speed: 0/sec
 ETA......: Unknown
 Elapsed..: 9 secs

Found Seed: hero,direct,wisdom,wool,expect,clerk,waste,casino,estate,burden,agent,try
Found Passphrase: test
```
